name: pervfi
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - boltons=23.0.0=py311h06a4308_0
  - brotlipy=0.7.0=py311h5eee18b_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py311h06a4308_0
  - cffi=1.15.1=py311h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda-content-trust=0.1.3=py311h06a4308_0
  - conda-package-handling=2.1.0=py311h06a4308_0
  - conda-package-streaming=0.8.0=py311h06a4308_0
  - cryptography=39.0.1=py311h9ce1e76_2
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.101=0
  - cuda-runtime=12.1.0=0
  - filelock=3.13.1=py311h06a4308_0
  - fmt=9.1.0=hdb19cb5_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2023.10.0=py311h06a4308_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libarchive=3.6.2=h6ac8c49_2
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.101=0
  - libcurl=8.1.1=h251f7ec_1
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libmamba=1.4.1=h2dafd23_1
  - libmambapy=1.4.1=py311h2dafd23_1
  - libnghttp2=1.52.0=h2d74bed_1
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libsolv=0.7.22=he621ea3_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxml2=2.10.3=hcbfbd50_0
  - lightning=2.2.0.post0=pyhd8ed1ab_0
  - lightning-utilities=0.9.0=py311h06a4308_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py311h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py311h06a4308_0
  - numpy=1.26.0=py311h08b1b3b_0
  - numpy-base=1.26.0=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - packaging=23.0=py311h06a4308_0
  - pcre2=10.37=he7ceb23_1
  - pillow=10.0.1=py311ha6cbd5a_0
  - pip=23.1.2=py311h06a4308_0
  - pluggy=1.0.0=py311h06a4308_1
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.4=py311h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.4=h955ad1f_0
  - pytorch=2.1.1=py3.11_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-lightning=2.0.3=py311h06a4308_0
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py311h5eee18b_0
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h295c915_1
  - reproc-cpp=14.2.4=h295c915_1
  - requests=2.29.0=py311h06a4308_0
  - ruamel.yaml=0.17.21=py311h5eee18b_0
  - setuptools=67.8.0=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.11.1=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py311h06a4308_0
  - torchaudio=2.1.1=py311_cu121
  - torchmetrics=1.1.2=py311h06a4308_0
  - torchtriton=2.1.0=py311
  - tqdm=4.65.0=py311h92b7b1e_0
  - typing-extensions=4.7.1=py311h06a4308_0
  - typing_extensions=4.7.1=py311h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py311h06a4308_0
  - wheel=0.38.4=py311h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.7.0=h295c915_1
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.19.0=py311h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.24.1
      - antlr4-python3-runtime==4.9.3
      - cupy-cuda12x==12.2.0
      - dists-pytorch==0.1
      - easydict==1.11
      - einops==0.7.0
      - fastrlock==0.8.2
      - grpcio==1.62.0
      - huggingface-hub==0.19.4
      - loguru==0.7.2
      - lpips==0.1.4
      - markdown==3.5.2
      - omegaconf==2.3.0
      - opencv-python==4.8.1.78
      - protobuf==4.25.3
      - psutil==5.9.6
      - pytorch-msssim==1.0.0
      - safetensors==0.4.0
      - scikit-video==1.1.11
      - scipy==1.11.4
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - timm==0.9.11
      - torchvision==0.16.1
      - werkzeug==3.0.1
      - yacs==0.1.8
prefix: /home/gywu/miniconda3/envs/pervfi
